// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLcOTzaSCP11FTiGCbb6MSmhGBhc1Tm8M',
    appId: '1:427273520173:web:1a16f50bc8a9cfdc2aa4a4',
    messagingSenderId: '427273520173',
    projectId: 'tik-tok-clone-99810',
    authDomain: 'tik-tok-clone-99810.firebaseapp.com',
    storageBucket: 'tik-tok-clone-99810.appspot.com',
    measurementId: 'G-VGCDSLD9XF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGYAsD3amxcTBA3eoe05lvq5N_0V-apcs',
    appId: '1:427273520173:android:004ca41e4b754ec32aa4a4',
    messagingSenderId: '427273520173',
    projectId: 'tik-tok-clone-99810',
    storageBucket: 'tik-tok-clone-99810.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhHiphlWSJ1OUAkU65wqIpOop8CXFsHvI',
    appId: '1:427273520173:ios:e6ddba4cbf645eab2aa4a4',
    messagingSenderId: '427273520173',
    projectId: 'tik-tok-clone-99810',
    storageBucket: 'tik-tok-clone-99810.appspot.com',
    iosClientId: '427273520173-79t4e3thu4gn8tifarkk7rv32geb32oq.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiktokClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhHiphlWSJ1OUAkU65wqIpOop8CXFsHvI',
    appId: '1:427273520173:ios:e6ddba4cbf645eab2aa4a4',
    messagingSenderId: '427273520173',
    projectId: 'tik-tok-clone-99810',
    storageBucket: 'tik-tok-clone-99810.appspot.com',
    iosClientId: '427273520173-79t4e3thu4gn8tifarkk7rv32geb32oq.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiktokClone',
  );
}
