// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5r6WPqILxL7-UyWFzYu7rjPZtNvKP9EM',
    appId: '1:347085566677:web:9c0f355f1ddb14d137685c',
    messagingSenderId: '347085566677',
    projectId: 'tik-tok-36baf',
    authDomain: 'tik-tok-36baf.firebaseapp.com',
    storageBucket: 'tik-tok-36baf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfBqNUGTVzPkImyH1IMwLYy2wCy2hf_Po',
    appId: '1:347085566677:android:58ddfabc0d7f0f9d37685c',
    messagingSenderId: '347085566677',
    projectId: 'tik-tok-36baf',
    storageBucket: 'tik-tok-36baf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuE9ldkjGdntGpsq6rPATtjhVh54uuaFk',
    appId: '1:347085566677:ios:04e29a5b8d77768e37685c',
    messagingSenderId: '347085566677',
    projectId: 'tik-tok-36baf',
    storageBucket: 'tik-tok-36baf.appspot.com',
    iosClientId: '347085566677-ficbqubmid87foslb8s6c2vt7kj6go3g.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiktokClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuE9ldkjGdntGpsq6rPATtjhVh54uuaFk',
    appId: '1:347085566677:ios:04e29a5b8d77768e37685c',
    messagingSenderId: '347085566677',
    projectId: 'tik-tok-36baf',
    storageBucket: 'tik-tok-36baf.appspot.com',
    iosClientId: '347085566677-ficbqubmid87foslb8s6c2vt7kj6go3g.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiktokClone',
  );
}
